/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author indrajith
 */
public class Main_v extends javax.swing.JFrame {

    /**
     * Creates new form Main_
     */
    public Main_v() {
        initComponents();
        
        
              
             ///////////////////ful scrn
         addWindowListener(new WindowAdapter() {
public void windowOpened(WindowEvent e) {
setExtendedState(MAXIMIZED_BOTH);
}
});
/////////////////////////////////////////////////////////////////!
    /*
show the time
*/
    
    setDateAndTime();
    
    }

    
     
     public void setDateAndTime()
    {
        System.out.println("success 11111 1");
        Thread d=new Thread()
        {  
            public void run()
            { System.out.println("success 22222");
                for(;;)
                {
                                    ////////////////////////////////////////////////
                                                        //date                      ////
                       DateFormat dateFormat=new SimpleDateFormat("dd - MM - YYYY");    ////
                      Calendar cal=Calendar.getInstance();                          ////

                      dsptoday.setText(dateFormat.format(cal.getTime()));           ////
                                           /////////
                                                        //time                      ////
                      DateFormat timeFormat = new SimpleDateFormat("hh : mm : ss  aa");     ////
                      Calendar clo = Calendar.getInstance();                        ////
                      dsptime.setText(timeFormat.format(clo.getTime()));            ////
              //        btime.setText(timeFormat.format(clo.getTime()));   /////////////////////
                                         ////////////////////////////////////////////////  
                                                
                             try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Log_in.class.getName()).log(Level.SEVERE, null, ex);
            }                               
                                                
                }
                    

        
            }
        };
//        System.out.print(xx);
//        if(xx==0)
             d.start();
//        else
//            d.stop();
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bs_main = new javax.swing.JLayeredPane();
        main0 = new javax.swing.JLayeredPane();
        main1 = new javax.swing.JLayeredPane();
        dsptoday = new javax.swing.JLabel();
        dsptime = new javax.swing.JLabel();
        bk_img = new javax.swing.JLayeredPane();
        bg_Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jDesktopPane1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        bs_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bs_mainMouseEntered(evt);
            }
        });

        main0.setPreferredSize(new java.awt.Dimension(1360, 768));
        main0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main0MouseEntered(evt);
            }
        });
        main0.setLayout(new javax.swing.OverlayLayout(main0));

        main1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        main1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                main1MouseEntered(evt);
            }
        });

        dsptoday.setFont(new java.awt.Font("LCD", 1, 18)); // NOI18N
        dsptoday.setForeground(new java.awt.Color(255, 255, 255));
        dsptoday.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        main1.add(dsptoday);
        dsptoday.setBounds(1140, 680, 200, 40);

        dsptime.setFont(new java.awt.Font("LCD", 1, 18)); // NOI18N
        dsptime.setForeground(new java.awt.Color(255, 255, 255));
        dsptime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        main1.add(dsptime);
        dsptime.setBounds(1130, 640, 210, 40);

        main0.add(main1);

        bs_main.add(main0);
        main0.setBounds(0, 0, 1370, 750);

        jDesktopPane1.add(bs_main);

        bk_img.setLayout(new javax.swing.OverlayLayout(bk_img));

        bg_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/000126029_prevstill.jpg"))); // NOI18N
        bk_img.add(bg_Image);

        jDesktopPane1.add(bk_img);

        jScrollPane1.setViewportView(jDesktopPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollBarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollBarUI());
        //UIManager.put("ScrollBarUI", "my.package.MyScrollBarUI");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void main1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main1MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_main1MouseEntered

    private void main0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main0MouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_main0MouseEntered

    private void bs_mainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bs_mainMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bs_mainMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_v().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_Image;
    private javax.swing.JLayeredPane bk_img;
    private javax.swing.JLayeredPane bs_main;
    private javax.swing.JLabel dsptime;
    private javax.swing.JLabel dsptoday;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLayeredPane main0;
    private javax.swing.JLayeredPane main1;
    // End of variables declaration//GEN-END:variables
}
